GET http://localhost:5023/games

###
GET http://localhost:5023/games/1

###
POST http://localhost:5023/games
Content-Type: application/json

{
  "title": "Escape from Tarkov",
  "genre": "Looter/Shooter",
  "price": 119.99,
  "releaseDate": "2020-07-23"
}